### PR TITLE
fix: 修复未开启多因子认证，人脸验证通过后还需验证指纹或密码才能进入桌面的问题

### PR DESCRIPTION
**Pull request by swq11**
在onRequestChangeAuth中增加判断当前类型是否是插件认证类型，不是插件类型则不会切换认证类型

Log: 修复未开启多因子认证，人脸验证通过后还需验证指纹或密码才能进入桌面的问题
Bug: https://pms.uniontech.com/bug-view-151591.html
Influence: 插件登录

### CODE REVIEW

**Review by wubw1992 — APPROVED** [review]

**Comment by swq11** [comment]
/check build-distribution / check_job / debian-build (pull_request_target)

**Comment by swq11** [comment]
/check build-distribution / check_job / debian-build (pull_request_target)

**Comment by swq11** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Pull request merged**
