### PR TITLE
fix: dependencies on archlinux

### PR DESCRIPTION
**Pull request by asterwyx**
Add dependencies on archlinux.

Log: fix dependencies on archlinux

### CODE REVIEW

**Comment by felixonmars** [comment]
What makes you think that it should be added here? I don't see deepin-pw-check mentioned anywhere in this repository.

**Comment by asterwyx** [comment]
> What makes you think that it should be added here? I don't see deepin-pw-check mentioned anywhere in this repository.

"deepin_pw_check.h" is included at src/lightdm-deepin-greeter/pwqualitymanager.h:10. You can also see libdeepin_pw_check.so required at CMakeLists.txt:247.

**Review by justforlxz — APPROVED** [review]

**Comment by justforlxz** [comment]
在下一个 pr 中删除 CMakeLists.txt 中无用的 flags。

**Comment by felixonmars** [comment]
I see. The change that brought isn't released yet so I overlooked it. However, deepin-pw-check would become a runtime dependency with the change in https://github.com/linuxdeepin/dde-session-shell/commit/8f728f28d15bc8e23bfbfef5c27cdf3a00bee1e0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL160 instead of just a makedepend.

**Comment by asterwyx** [comment]
> I see. The change that brought isn't released yet so I overlooked it. However, deepin-pw-check would become a runtime dependency with the change in [8f728f2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL160](https://github.com/linuxdeepin/dde-session-shell/commit/8f728f28d15bc8e23bfbfef5c27cdf3a00bee1e0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL160) instead of just a makedepend.

OK, I will add it to depends right at the next commit. Thanks for your correction.

**Pull request merged**
